{"uid":"8696706c83d8114d","name":"test_scenario_3_orders","fullName":"tests.tests_steps.TestScenario3orders#test_scenario_3_orders","historyId":"00f7485f22028d496ac230dc80af8a94","time":{"start":1659522401966,"stop":1659522404353,"duration":2387},"status":"failed","statusMessage":"AssertionError","statusTrace":"self = <tests_steps.TestScenario3orders object at 0x7f521c46f130>\n\n    def test_scenario_3_orders(self):\n        test_scenario_3 = Scenario_Three()\n>       test_scenario_3.go_to_your_orders()\n\ntests/tests_steps.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.Scenario3.Scenario_Three object at 0x7f521c33d9f0>\n\n    @allure.step(\"Go to Your Orders\")\n    def go_to_your_orders(self):\n        self.visit(self.base_url)\n        self.targeting(*self.locator_dictionary['buttonGoToSignIn'])\n        self.find_element(*self.locator_dictionary['buttonYourOrders']).click()\n>       assert 1 == 2\nE       AssertionError\n\npages/Scenario3.py:19: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"start_session","time":{"start":1659522398728,"stop":1659522401965,"duration":3237},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"status":"failed","statusMessage":"AssertionError","statusTrace":"self = <tests_steps.TestScenario3orders object at 0x7f521c46f130>\n\n    def test_scenario_3_orders(self):\n        test_scenario_3 = Scenario_Three()\n>       test_scenario_3.go_to_your_orders()\n\ntests/tests_steps.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.Scenario3.Scenario_Three object at 0x7f521c33d9f0>\n\n    @allure.step(\"Go to Your Orders\")\n    def go_to_your_orders(self):\n        self.visit(self.base_url)\n        self.targeting(*self.locator_dictionary['buttonGoToSignIn'])\n        self.find_element(*self.locator_dictionary['buttonYourOrders']).click()\n>       assert 1 == 2\nE       AssertionError\n\npages/Scenario3.py:19: AssertionError","steps":[{"name":"Go to Your Orders","time":{"start":1659522401966,"stop":1659522404353,"duration":2387},"status":"failed","statusMessage":"AssertionError\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/autotetsamazon/autotetsamazon/pages/Scenario3.py\", line 19, in go_to_your_orders\n    assert 1 == 2\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"attachments":[{"uid":"64f6dbcb98455fd2","name":"Current URL","source":"64f6dbcb98455fd2.uri","type":"text/uri-list","size":22},{"uid":"757e64ed5fba2210","name":"Screenshot","source":"757e64ed5fba2210.png","type":"image/png","size":34524}],"parameters":[],"stepsCount":1,"attachmentsCount":2,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[{"name":"start_session::0","time":{"start":1659522404529,"stop":1659522404589,"duration":60},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_session')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"tests_steps"},{"name":"subSuite","value":"TestScenario3orders"},{"name":"host","value":"fv-az119-838"},{"name":"thread","value":"2252-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.tests_steps"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":4,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":6},"items":[{"uid":"d8953b1f1c63fa15","reportUrl":"https://Spirlhark.github.io/autotetsamazon/4//#testresult/d8953b1f1c63fa15","status":"failed","statusDetails":"AssertionError","time":{"start":1659511876565,"stop":1659511878949,"duration":2384}},{"uid":"cae50871643bad5d","reportUrl":"https://Spirlhark.github.io/autotetsamazon/3//#testresult/cae50871643bad5d","status":"failed","statusDetails":"AssertionError","time":{"start":1659468866969,"stop":1659468870466,"duration":3497}},{"uid":"b6cb1f70e7912010","reportUrl":"https://Spirlhark.github.io/autotetsamazon/3//#testresult/b6cb1f70e7912010","status":"failed","statusDetails":"AssertionError","time":{"start":1659460426852,"stop":1659460429508,"duration":2656}},{"uid":"f841dbf164847c70","reportUrl":"https://Spirlhark.github.io/autotetsamazon/2//#testresult/f841dbf164847c70","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x561b0c0b6cd3 <unknown>\n#1 0x561b0bebe968 <unknown>\n#2 0x561b0bee325c <unknown>\n#3 0x561b0bede8fa <unknown>\n#4 0x561b0bf1994a <unknown>\n#5 0x561b0bf13aa3 <unknown>\n#6 0x561b0bee93fa <unknown>\n#7 0x561b0beea555 <unknown>\n#8 0x561b0c0fe2bd <unknown>\n#9 0x561b0c102418 <unknown>\n#10 0x561b0c0e836e <unknown>\n#11 0x561b0c103078 <unknown>\n#12 0x561b0c0dcbb0 <unknown>\n#13 0x561b0c11fd58 <unknown>\n#14 0x561b0c11fed8 <unknown>\n#15 0x561b0c139cfd <unknown>\n#16 0x7ffa901b0609 <unknown>","time":{"start":1659439730786,"stop":1659439730786,"duration":0}},{"uid":"4d5ab36737c5924b","reportUrl":"https://Spirlhark.github.io/autotetsamazon/1//#testresult/4d5ab36737c5924b","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x560f33f0bcd3 <unknown>\n#1 0x560f33d13968 <unknown>\n#2 0x560f33d3825c <unknown>\n#3 0x560f33d338fa <unknown>\n#4 0x560f33d6e94a <unknown>\n#5 0x560f33d68aa3 <unknown>\n#6 0x560f33d3e3fa <unknown>\n#7 0x560f33d3f555 <unknown>\n#8 0x560f33f532bd <unknown>\n#9 0x560f33f57418 <unknown>\n#10 0x560f33f3d36e <unknown>\n#11 0x560f33f58078 <unknown>\n#12 0x560f33f31bb0 <unknown>\n#13 0x560f33f74d58 <unknown>\n#14 0x560f33f74ed8 <unknown>\n#15 0x560f33f8ecfd <unknown>\n#16 0x7fc7d4fe1609 <unknown>","time":{"start":1659438874791,"stop":1659438874791,"duration":0}}]},"tags":["@pytest.mark.usefixtures('start_session')"]},"source":"8696706c83d8114d.json","parameterValues":[]}